name = "GeneralizedMonteCarlo"
uuid = "e9bfd9a4-9025-4baf-81dc-99e507987dd3"
authors = ["scottggreenberg <s.greenberg@aggiemail.usu.edu>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
